CREATE SEQUENCE IF NOT EXISTS dpp_metadata_seq;

CREATE TABLE IF NOT EXISTS dpp_metadata (
id BIGINT PRIMARY KEY DEFAULT nextval('ddp_metadata_seq'),
registry_id VARCHAR(36) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
modified_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
metadata JSONB NOT NULL
);

CREATE SEQUENCE IF NOT EXISTS json_schema_seq;

CREATE TABLE IF NOT EXISTS json_schemas (
id BIGINT PRIMARY KEY DEFAULT nextval('json_schema_seq'),
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
data_schema JSONB NOT NULL
);